### ISSUE TITLE
NPM not found

### ISSUE THREAD

**Issue by freynolds** [thoughtbot/react-native-settings-url#2]
Hey, nice simple plugin. I can't find it in NPM 
I've instaled via git hub, so far so good
`npm install --save https://github.com/thoughtbot/react-native-settings-url`

Just giving you the heads up, maybe its in a private repo?

My regards!

**Comment by tysongach** [comment]
I don't believe it was ever fully published to npm. At this time, we're no longer maintaining and are archiving the repo (making it read-only).
